[build]
command = "cd server && npm ci && npm run build"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production" 