version: '3.8'
services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_DB: test_oneshot
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_oneshot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test_db_data: 